[tool.poetry]
name = "btc-price-prediction"
version = "0.1.0"
description = ""
authors = ["katori0508 <theanh0508@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
